Namespace Global.QB.CodeAnalysis.Syntax

  Public Enum SyntaxKind

    BadToken
    EndOfFileToken

    Label

    ' Trivia
    LineNumberTrivia
    SkippedTextTrivia
    LineBreakTrivia
    WhiteSpaceTrivia
    SingleLineCommentTrivia

    ' Tokens
    BackslashToken
    CloseBraceToken
    CloseParenToken
    ColonToken
    CommaToken
    EqualToken
    GreaterThanEqualToken
    GreaterThanToken
    HatToken
    IdentifierToken
    LessThanEqualToken
    LessThanGreaterThanToken
    LessThanToken
    MinusToken
    OpenBraceToken
    OpenParenToken
    PeriodToken
    PlusToken
    PoundToken
    QuestionToken
    SemicolonToken
    SlashToken
    StarToken
    StringToken

    NumberToken
    'ExclamationToken
    'AmpersandToken
    'PercentToken

    ' Keywords

    AndAlsoKeyword
    AndKeyword
    AnyKeyword
    AsKeyword
    BaseKeyword
    ChDirKeyword
    ClearKeyword
    ClsKeyword
    ColorKeyword
    CommonKeyword
    ConstKeyword
    ContinueKeyword
    ContinueDoKeyword
    ContinueForKeyword
    ContinueWhileKeyword
    DataKeyword
    DefKeyword
    DefDblKeyword
    DefIntKeyword
    DefLngKeyword
    DefSngKeyword
    DefStrKeyword
    DimKeyword
    DoKeyword
    EachKeyword
    ElseIfKeyword
    ElseKeyword
    EndKeyword
    EndDefKeyword
    EndFunctionKeyword
    EndSubKeyword
    EndIfKeyword
    EndTypeKeyword
    EqvKeyword
    EraseKeyword
    ErrorKeyword
    ExitKeyword
    ExitDefKeyword
    ExitFunctionKeyword
    ExitSubKeyword
    ExitDoKeyword
    ExitForKeyword
    ExitWhileKeyword
    FalseKeyword
    ForKeyword
    FunctionKeyword
    GosubKeyword
    GotoKeyword
    IfKeyword
    ImpKeyword
    InKeyword
    InputKeyword
    KillKeyword
    LetKeyword
    LineKeyword
    LineInputKeyword
    LocateKeyword
    LockKeyword
    LoopKeyword
    MidKeyword
    MkDirKeyword
    ModKeyword
    NameKeyword
    NextKeyword
    NotKeyword
    OptionKeyword
    OrElseKeyword
    OrKeyword
    PrintKeyword
    RandomKeyword
    RandomizeKeyword
    ReadKeyword
    RedimKeyword
    RemKeyword
    ResetKeyword
    RestoreKeyword
    ReturnKeyword
    RmDirKeyword
    SharedKeyword
    SpcKeyword
    SleepKeyword
    StaticKeyword
    StepKeyword
    StopKeyword
    SubKeyword
    SwapKeyword
    SystemKeyword
    TabKeyword
    ThenKeyword
    ToKeyword
    TrueKeyword
    TypeKeyword
    UnlockKeyword
    UntilKeyword
    WendKeyword
    WhileKeyword
    WidthKeyword
    WindowKeyword
    WriteKeyword
    XorKeyword

    ' Nodes
    AsClause
    CompilationUnit
    DefDeclaration
    FunctionDeclaration
    GlobalStatement
    InitClause
    LowerSubscriptClause
    Parameter
    SingleLineElseClause
    SubscriptClause
    UntilClause
    WhileClause

    ' Functions
    SpcFunction
    TabFunction

    ' Statements
    BlockStatement
    ChDirStatement
    ClearStatement
    ClsStatement
    ColorStatement
    ContinueStatement
    DataStatement
    DoUntilStatement
    DoWhileStatement
    EndStatement
    ElseIfStatement
    ElseStatement
    ExitStatement
    ExpressionStatement
    ForEachStatement
    ForStatement
    GosubStatement
    GotoStatement
    IfStatement
    InputStatement
    KillStatement
    LabelStatement
    LetStatement
    MidStatement
    MkDirStatement
    MultiLineIfBlock
    NameStatement
    OptionStatement
    PrintStatement
    ReadStatement
    RemStatement
    RestoreStatement
    ReturnGosubStatement
    ReturnStatement
    RmDirStatement
    SingleLineDefDeclaration
    SingleLineIfStatement
    StopStatement
    SystemStatement
    VariableDeclarationStatement
    WhileStatement

    ' Expressions
    AssignmentExpression
    BinaryExpression
    CallExpression
    LiteralExpression
    NameExpression
    ParenExpression
    UnaryExpression

    ' Newly added 3/15...
    AbsoluteKeyword
    AccessKeyword
    BeepKeyword
    BloadKeyword
    BsaveKeyword
    CallKeyword
    CaseKeyword
    ChainKeyword
    CircleKeyword
    CloseKeyword
    ComKeyword
    DateKeyword
    DeclareKeyword
    DoubleKeyword
    DrawKeyword
    EndSelectKeyword
    EnvironKeyword
    FieldKeyword
    FilesKeyword
    GetKeyword
    IntegerKeyword
    IoCtlKeyword
    KeyKeyword
    ListKeyword
    LongKeyword
    LPrintKeyword
    LSetKeyword
    OffKeyword
    OnKeyword
    OpenKeyword
    OutKeyword
    PaintKeyword
    PaletteKeyword
    PCopyKeyword
    PeekKeyword
    PenKeyword
    PlayKeyword
    PokeKeyword
    PResetKeyword
    PSetKeyword
    PutKeyword
    ResumeKeyword
    RSetKeyword
    RunKeyword
    ScreenKeyword
    SegKeyword
    SeekKeyword
    SelectKeyword
    ShellKeyword
    SingleKeyword
    SoundKeyword
    StrigKeyword
    StringKeyword
    TimeKeyword
    TimerKeyword
    TroffKeyword
    TronKeyword
    UsingKeyword
    ViewKeyword
    WaitKeyword
    AppendKeyword
    BinaryKeyword
    IsKeyword
    OutputKeyword
    StickKeyword
  End Enum

End Namespace