Namespace Global.QB.CodeAnalysis.Syntax

  Public Enum SyntaxKind

    TrueKeyword
    FalseKeyword
    AndAlsoKeyword
    OrElseKeyword

    BadToken

    ' Trivia
    LineNumberTrivia
    SkippedTextTrivia
    LineBreakTrivia
    WhiteSpaceTrivia
    SingleLineCommentTrivia
    LineContinuationTrivia
    EndOfFileToken

#Region "SpecBAS"

    AtKeyword
    AutoKeyword
    BorderKeyword
    DefaultKeyword
    FillKeyword
    FullKeyword
    GoKeyword
    GrabKeyword
    HsvKeyword
    IncKeyword
    InkKeyword
    InverseKeyword
    MoveKeyword
    OverKeyword
    PaperKeyword
    ProgKeyword
    ShlKeyword
    ShrKeyword
    UpdateKeyword
    ZxAsciiKeyword

    SbAtClause
    SbAutoStatement
    SbBorderStatement
    SbCircleStatement
    SbGotoStatement
    SbGosubStatement
    SbIncStatement
    SbInkStatement
    SbInverseStatement
    SbMoveStatement
    SbOverStatement
    SbPaletteDefaultStatement
    SbPaletteHsvStatement
    SbPaletteShiftStatement
    SbPaletteStatement
    SbPaperStatement
    SbProgStatement
    SbScreenStatement
    SbWaitStatement
    SbZxAsciiStatement

#End Region

    ' Tokens
    Label
    BackslashToken
    CloseBraceToken
    CloseParenToken
    ColonToken
    CommaToken
    EqualToken
    GreaterThanEqualToken
    GreaterThanToken
    HatToken
    IdentifierToken
    LessThanEqualToken
    LessThanGreaterThanToken
    LessThanToken
    MinusToken
    OpenBraceToken
    OpenParenToken
    PeriodToken
    PlusToken
    PoundToken
    QuestionToken
    SemicolonToken
    SlashToken
    StarToken
    StringToken
    NumberToken
    'ExclamationToken
    'AmpersandToken
    'PercentToken

    ' Keywords

    AbsoluteKeyword
    AccessKeyword
    AndKeyword
    'AndAlsoKeyword
    AnyKeyword
    AppendKeyword
    AsKeyword
    BaseKeyword
    BeepKeyword
    BinaryKeyword
    BLoadKeyword
    BSaveKeyword
    CallKeyword
    CaseKeyword
    ChainKeyword
    ChDirKeyword
    CircleKeyword
    ClearKeyword
    CloseKeyword
    ClsKeyword
    ColorKeyword
    ComKeyword
    CommonKeyword
    ConstKeyword
    ContinueKeyword
    ContinueDoKeyword
    ContinueForKeyword
    ContinueWhileKeyword
    DataKeyword
    DateKeyword
    DeclareKeyword
    DefKeyword
    DefDblKeyword
    DefIntKeyword
    DefLngKeyword
    DefSngKeyword
    DefStrKeyword
    DimKeyword
    DoKeyword
    DoubleKeyword
    DrawKeyword
    'EachKeyword
    ElseKeyword
    ElseIfKeyword
    EndKeyword
    'EndDefKeyword
    'EndFunctionKeyword
    'EndIfKeyword
    'EndSelectKeyword
    'EndSubKeyword
    'EndTypeKeyword
    EnvironKeyword
    EqvKeyword
    EraseKeyword
    ErrorKeyword
    ExitKeyword
    ExitDefKeyword
    ExitDoKeyword
    ExitForKeyword
    ExitFunctionKeyword
    ExitSubKeyword
    ExitWhileKeyword
    'FalseKeyword
    FieldKeyword
    FilesKeyword
    ForKeyword
    FunctionKeyword
    GetKeyword
    GosubKeyword
    GotoKeyword
    IfKeyword
    ImpKeyword
    'InKeyword
    InputKeyword
    IntegerKeyword
    IoCtlKeyword
    IsKeyword
    KeyKeyword
    KillKeyword
    LenKeyword
    LetKeyword
    LineKeyword
    LineInputKeyword
    ListKeyword
    LocateKeyword
    LockKeyword
    LongKeyword
    LoopKeyword
    LPrintKeyword
    LSetKeyword
    MidKeyword
    MkDirKeyword
    ModKeyword
    NameKeyword
    NextKeyword
    NotKeyword
    OffKeyword
    OnKeyword
    OpenKeyword
    OptionKeyword
    OrKeyword
    'OrElseKeyword
    OutKeyword
    OutputKeyword
    PaintKeyword
    PaletteKeyword
    PCopyKeyword
    'PeekKeyword
    PenKeyword
    PlayKeyword
    PokeKeyword
    PresetKeyword
    PreserveKeyword
    PrintKeyword
    PsetKeyword
    PutKeyword
    RandomKeyword
    RandomizeKeyword
    ReadKeyword
    RedimKeyword
    RedimPreserveKeyword
    RemKeyword
    ResetKeyword
    RestoreKeyword
    ResumeKeyword
    ReturnKeyword
    RmDirKeyword
    RSetKeyword
    RunKeyword
    ScreenKeyword
    SeekKeyword
    SegKeyword
    SelectKeyword
    SharedKeyword
    ShellKeyword
    SingleKeyword
    SleepKeyword
    SoundKeyword
    SpcKeyword
    StaticKeyword
    StepKeyword
    StickKeyword
    StopKeyword
    StrigKeyword
    StringKeyword
    SubKeyword
    SwapKeyword
    SystemKeyword
    TabKeyword
    ThenKeyword
    TimeKeyword
    TimerKeyword
    ToKeyword
    TroffKeyword
    TronKeyword
    'TrueKeyword
    TypeKeyword
    UnlockKeyword
    UntilKeyword
    UsingKeyword
    ViewKeyword
    WaitKeyword
    WendKeyword
    WhileKeyword
    WidthKeyword
    WindowKeyword
    WriteKeyword
    XorKeyword

    ' Nodes
    AsClause
    CaseClause
    CaseElseClause
    CaseMatchExpression
    CompilationUnit
    DefDeclaration
    DefVarRangeClause
    DimensionClause
    DimensionsClause
    FunctionDeclaration
    GlobalStatement
    InitClause
    Parameter
    SingleLineElseClause
    UntilClause
    WhileClause

    ' Functions
    SpcFunction
    TabFunction

    ' Statements
    BlockStatement
    IdentifierSyntax
    MultiLineIfBlock
    SingleLineDefDeclaration
    SingleLineIfStatement
    StatementSeparatorStatement
    VariableDeclaration
    VariableDeclarationStatement

    BeepStatement
    BloadStatement
    BsaveStatement
    CallStatement
    ChainStatement
    ChDirStatement
    CircleStatement
    ClearStatement
    CloseStatement
    ClsStatement
    ColorStatement
    ComStatement
    CommonStatement
    ConstStatement
    ContinueStatement
    DateStatement
    DeclareStatement
    DefSegStatement
    DefTypeStatement
    DimStatement
    DataStatement
    DoUntilStatement
    DoWhileStatement
    DrawStatement
    EndStatement
    ElseIfStatement
    ElseStatement
    EnvironStatement
    EraseStatement
    ErrorStatement
    ExitStatement
    ExpressionStatement
    FieldStatement
    FilesStatement
    'ForEachStatement
    ForStatement
    FunctionStatement
    GetStatement
    GetFileStatement
    GosubStatement
    GotoStatement
    IfStatement
    InputStatement
    IoCtlStatement
    KeyStatement
    KeyListStatement
    KeyOffStatement
    KeyOnStatement
    KillStatement
    LabelStatement
    LetStatement
    LineStatement
    LineInputStatement
    LineInputFileStatement
    LocateStatement
    LockStatement
    LockRangeStatement
    LprintStatement
    LsetStatement
    MidStatement
    MkDirStatement
    NameStatement
    OnErrorGotoStatement
    OnGotoStatement
    OnGosubStatement
    OnTimerGosubStatement
    OnComGosubStatement
    OnKeyGosubStatement
    OnStrigGosubStatement
    OnPlayGosubStatement
    OnPenGosubStatement
    KeyEventStatement
    PlayEventStatement
    OpenStatement
    OptionStatement
    OutStatement
    PaintStatement
    PcopyStatement
    PenStatement
    PlayStatement
    PokeStatement
    PrintStatement
    PutStatement
    PutFileStatement
    RandomizeStatement
    ReadStatement
    RedimStatement
    RemStatement
    ResetStatement
    RestoreStatement
    ResumeStatement
    ResumeNextStatement
    NextStatement
    ReturnGosubStatement
    ReturnStatement
    RmDirStatement
    RsetStatement
    RunStatement
    SeekStatement
    SelectCaseStatement
    SharedStatement
    ShellStatement
    SleepStatement
    SoundStatement
    StaticStatement
    StopStatement
    StrigStatement
    SubStatement
    SwapStatement
    SystemStatement
    TimeStatement
    TimerStatement
    TroffStatement
    TronStatement
    UnlockStatement
    UnlockRangeStatement
    ViewStatement
    ViewPrintStatement
    WaitStatement
    WhileStatement
    WidthStatement
    WidthFileStatement
    WidthLprintStatement
    WindowStatement
    WriteStatement

    ' Expressions
    AssignmentExpression
    ArrayAccessExpression
    BinaryExpression
    CallExpression
    LiteralExpression
    NameExpression
    ParenExpression
    UnaryExpression

    ' End Block
    EndTypeStatement
    EndIfStatement
    'EndUsingStatement
    'EndWithStatement
    EndSelectStatement
    'EndStructureStatement
    'EndEnumStatement
    'EndInterfaceStatement
    'EndClassStatement
    'EndModuleStatement
    'EndNamespaceStatement
    EndSubStatement
    EndFunctionStatement
    'EndGetStatement
    'EndSetStatement
    'EndPropertyStatement
    'EndOperatorStatement
    'EndEventStatement
    'EndAddHandlerStatement
    'EndRemoveHandlerStatement
    'EndRaiseEventStatement
    'EndWhileStatement
    'EndTryStatement
    'EndSyncLockStatement

    ForStepClause

  End Enum

End Namespace