Imports System.Collections.Immutable
Imports System.Reflection

Namespace Global.QB.CodeAnalysis.Symbols

  Friend Module BuiltinFunctions

    'Public ReadOnly Print As New FunctionSymbol("print", ImmutableArray.Create(New ParameterSymbol("text", TypeSymbol.String, 0)), TypeSymbol.Nothing)
    'Public ReadOnly Input As New FunctionSymbol("input", ImmutableArray(Of ParameterSymbol).Empty, TypeSymbol.String)

    Public ReadOnly Abs As New FunctionSymbol("abs", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.Single, 0)), TypeSymbol.Single)
    Public ReadOnly Asc As New FunctionSymbol("asc", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.String)), TypeSymbol.Long)
    Public ReadOnly Atn As New FunctionSymbol("atn", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.Single, 0)), TypeSymbol.Single)
    Public ReadOnly [CDbl] As New FunctionSymbol("cdbl", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.Double, 0)), If(OPTION_DOUBLE, TypeSymbol.Double, TypeSymbol.Single))
    Public ReadOnly [CInt] As New FunctionSymbol("cint", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.Double, 0)), If(OPTION_DOUBLE, TypeSymbol.Double, TypeSymbol.Single))
    Public ReadOnly [CLng] As New FunctionSymbol("clng", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.Double, 0)), If(OPTION_DOUBLE, TypeSymbol.Double, TypeSymbol.Single))
    Public ReadOnly Cos As New FunctionSymbol("cos", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.Single, 0)), TypeSymbol.Single)
    Public ReadOnly [CSng] As New FunctionSymbol("csng", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.Double, 0)), If(OPTION_DOUBLE, TypeSymbol.Double, TypeSymbol.Single))
    'Public ReadOnly CsrLin As New FunctionSymbol("csrlin", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.Double, 0)), If(OPTION_DOUBLE, TypeSymbol.Double, TypeSymbol.Single))
    Public ReadOnly CsrLin As New FunctionSymbol("csrlin", ImmutableArray(Of ParameterSymbol).Empty, TypeSymbol.Integer)
    Public ReadOnly Cvd As New FunctionSymbol("cvd", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.String, 0)), TypeSymbol.Double)
    Public ReadOnly CvdMbf As New FunctionSymbol("cvdmbf", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.String, 0)), TypeSymbol.Double)
    Public ReadOnly Cvi As New FunctionSymbol("cvi", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.String)), TypeSymbol.Integer)
    Public ReadOnly Cvl As New FunctionSymbol("cvl", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.String, 0)), TypeSymbol.Long)
    Public ReadOnly Cvs As New FunctionSymbol("cvs", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.String)), TypeSymbol.Single)
    Public ReadOnly CvsMbf As New FunctionSymbol("cvsmbf", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.String, 0)), TypeSymbol.Single)
    ' exp
    Public ReadOnly Eof As New FunctionSymbol("eof", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.Double, 0)), TypeSymbol.Double)
    Public ReadOnly ErDev1 As New FunctionSymbol("erdev", ImmutableArray(Of ParameterSymbol).Empty, TypeSymbol.Integer)
    Public ReadOnly ErDev2 As New FunctionSymbol("erdev$", ImmutableArray(Of ParameterSymbol).Empty, TypeSymbol.String)
    Public ReadOnly Erl As New FunctionSymbol("erl", ImmutableArray(Of ParameterSymbol).Empty, TypeSymbol.Integer)
    Public ReadOnly Err As New FunctionSymbol("err", ImmutableArray(Of ParameterSymbol).Empty, TypeSymbol.Integer)
    Public ReadOnly Exp As New FunctionSymbol("exp", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.Single, 0)), TypeSymbol.Single)
    Public ReadOnly FileAttr As New FunctionSymbol("fileattr", ImmutableArray.Create(New ParameterSymbol("value1", TypeSymbol.Any), New ParameterSymbol("value2", TypeSymbol.Any)), TypeSymbol.Integer)
    Public ReadOnly Fix As New FunctionSymbol("fix", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.Single, 0)), TypeSymbol.Single)
    Public ReadOnly Fre As New FunctionSymbol("fre", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.Any, 0)), TypeSymbol.Single)
    'Public ReadOnly FreeFile As New FunctionSymbol("freefile", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.Double, 0)), TypeSymbol.Double)
    Public ReadOnly FreeFile As New FunctionSymbol("freefile", ImmutableArray(Of ParameterSymbol).Empty, TypeSymbol.Integer)
    Public ReadOnly Int As New FunctionSymbol("int", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.Single, 0)), TypeSymbol.Single)
    Public ReadOnly Inp As New FunctionSymbol("inp", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.Double, 0)), TypeSymbol.Double)
    Public ReadOnly LBound As New FunctionSymbol("lbound", ImmutableArray.Create(New ParameterSymbol("lbound", TypeSymbol.Any)), TypeSymbol.Long)
    Public ReadOnly Len As New FunctionSymbol("len", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.String)), TypeSymbol.Long)
    Public ReadOnly Loc As New FunctionSymbol("loc", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.Double, 0)), If(OPTION_DOUBLE, TypeSymbol.Double, TypeSymbol.Single))
    Public ReadOnly Lof As New FunctionSymbol("lof", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.Double, 0)), If(OPTION_DOUBLE, TypeSymbol.Double, TypeSymbol.Single))
    Public ReadOnly Log As New FunctionSymbol("log", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.Single, 0)), TypeSymbol.Single)
    Public ReadOnly Lpos As New FunctionSymbol("lpos", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.Double, 0)), If(OPTION_DOUBLE, TypeSymbol.Double, TypeSymbol.Single))
    Public ReadOnly Peek As New FunctionSymbol("peek", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.Single, 0)), TypeSymbol.Integer)
    Public ReadOnly Pen As New FunctionSymbol("pen", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.Single, 0)), TypeSymbol.Integer)
    Public ReadOnly Play As New FunctionSymbol("play", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.Single, 0)), TypeSymbol.Integer)
    Public ReadOnly Pmap As New FunctionSymbol("pmap", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.Double, 0)), If(OPTION_DOUBLE, TypeSymbol.Double, TypeSymbol.Single))
    Public ReadOnly Point As New FunctionSymbol("point", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.Double, 0)), If(OPTION_DOUBLE, TypeSymbol.Double, TypeSymbol.Single))
    Public ReadOnly Pos As New FunctionSymbol("pos", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.Double, 0)), If(OPTION_DOUBLE, TypeSymbol.Double, TypeSymbol.Single))
    Public ReadOnly Rnd1 As New FunctionSymbol("rnd", ImmutableArray(Of ParameterSymbol).Empty, TypeSymbol.Single)
    Public ReadOnly Rnd2 As New FunctionSymbol("rnd", ImmutableArray.Create(New ParameterSymbol("opt", TypeSymbol.Double, 0)), TypeSymbol.Single)
    'Public ReadOnly Screen As New FunctionSymbol("screen", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.Double, 0)), TypeSymbol.Long)
    Public ReadOnly Seek As New FunctionSymbol("seek", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.Double, 0)), TypeSymbol.Long)
    Public ReadOnly Sgn As New FunctionSymbol("sgn", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.Double, 0)), TypeSymbol.Long)
    Public ReadOnly Sin As New FunctionSymbol("sin", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.Single, 0)), TypeSymbol.Single)
    Public ReadOnly Sqr As New FunctionSymbol("sqr", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.Single, 0)), TypeSymbol.Single)
    Public ReadOnly Stick As New FunctionSymbol("stick", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.Single, 0)), TypeSymbol.Integer)
    Public ReadOnly Strig As New FunctionSymbol("strig", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.Single, 0)), TypeSymbol.Integer)
    Public ReadOnly Tan As New FunctionSymbol("tan", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.Single, 0)), TypeSymbol.Single)
    Public ReadOnly Timer As New FunctionSymbol("timer", ImmutableArray(Of ParameterSymbol).Empty, TypeSymbol.Single)
    Public ReadOnly UBound As New FunctionSymbol("ubound", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.Any)), TypeSymbol.Long)
    Public ReadOnly Val As New FunctionSymbol("val", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.String)), TypeSymbol.Double)
    Public ReadOnly VarPtr1 As New FunctionSymbol("varptr", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.Any)), TypeSymbol.Integer)
    Public ReadOnly VarSeg As New FunctionSymbol("varseg", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.Any)), TypeSymbol.Double)

    Public ReadOnly Screen1 As New FunctionSymbol("screen", ImmutableArray.Create(New ParameterSymbol("row", TypeSymbol.Single), New ParameterSymbol("column", TypeSymbol.Single)), TypeSymbol.Integer)
    Public ReadOnly Screen2 As New FunctionSymbol("screen", ImmutableArray.Create(New ParameterSymbol("row", TypeSymbol.Single), New ParameterSymbol("column", TypeSymbol.Single), New ParameterSymbol("colr", TypeSymbol.Single)), TypeSymbol.Integer)

    Public ReadOnly Chr As New FunctionSymbol("chr$", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.Single)), TypeSymbol.String)
    Public ReadOnly Command As New FunctionSymbol("command$", ImmutableArray(Of ParameterSymbol).Empty, TypeSymbol.String)
    'Public ReadOnly [Date] As New FunctionSymbol("date$", ImmutableArray.Create(New ParameterSymbol("num", TypeSymbol.Long)), TypeSymbol.String)
    Public ReadOnly [Date] As New FunctionSymbol("date$", ImmutableArray(Of ParameterSymbol).Empty, TypeSymbol.String)
    Public ReadOnly Environ As New FunctionSymbol("environ$", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.Any)), TypeSymbol.String)
    Public ReadOnly Hex As New FunctionSymbol("hex$", ImmutableArray.Create(New ParameterSymbol("num", TypeSymbol.Single)), TypeSymbol.String)
    Public ReadOnly Inkey As New FunctionSymbol("inkey$", ImmutableArray(Of ParameterSymbol).Empty, TypeSymbol.String)
    Public ReadOnly Input As New FunctionSymbol("input$", ImmutableArray.Create(New ParameterSymbol("num", TypeSymbol.Long)), TypeSymbol.String)
    Public ReadOnly IoCtl As New FunctionSymbol("ioctl$", ImmutableArray.Create(New ParameterSymbol("num", TypeSymbol.Long)), TypeSymbol.String)
    Public ReadOnly LCase As New FunctionSymbol("lcase$", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.String)), TypeSymbol.String)
    Public ReadOnly Left As New FunctionSymbol("left$", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.String), New ParameterSymbol("num", TypeSymbol.Long)), TypeSymbol.String)
    Public ReadOnly Ltrim As New FunctionSymbol("ltrim$", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.String)), TypeSymbol.String)
    Public ReadOnly Mkd As New FunctionSymbol("mkd$", ImmutableArray.Create(New ParameterSymbol("num", TypeSymbol.Double)), TypeSymbol.String)
    Public ReadOnly MkdMbf As New FunctionSymbol("mkdmbf$", ImmutableArray.Create(New ParameterSymbol("num", TypeSymbol.Double)), TypeSymbol.String)
    Public ReadOnly Mki As New FunctionSymbol("mki$", ImmutableArray.Create(New ParameterSymbol("num", TypeSymbol.Integer)), TypeSymbol.String)
    Public ReadOnly Mkl As New FunctionSymbol("mkl$", ImmutableArray.Create(New ParameterSymbol("num", TypeSymbol.Long)), TypeSymbol.String)
    Public ReadOnly Mks As New FunctionSymbol("mks$", ImmutableArray.Create(New ParameterSymbol("num", TypeSymbol.Single)), TypeSymbol.String)
    Public ReadOnly MksMbf As New FunctionSymbol("mksmbf$", ImmutableArray.Create(New ParameterSymbol("num", TypeSymbol.Single)), TypeSymbol.String)
    Public ReadOnly Oct As New FunctionSymbol("oct$", ImmutableArray.Create(New ParameterSymbol("num", TypeSymbol.Single)), TypeSymbol.String)
    Public ReadOnly Right As New FunctionSymbol("right$", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.String), New ParameterSymbol("num", TypeSymbol.Long)), TypeSymbol.String)
    Public ReadOnly Rtrim As New FunctionSymbol("rtrim$", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.String)), TypeSymbol.String)
    Public ReadOnly Space As New FunctionSymbol("space$", ImmutableArray.Create(New ParameterSymbol("num", TypeSymbol.Single)), TypeSymbol.String)
    Public ReadOnly Str As New FunctionSymbol("str$", ImmutableArray.Create(New ParameterSymbol("num", TypeSymbol.Single)), TypeSymbol.String)
    Public ReadOnly Time As New FunctionSymbol("time$", ImmutableArray(Of ParameterSymbol).Empty, TypeSymbol.String)
    Public ReadOnly UCase As New FunctionSymbol("ucase$", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.String)), TypeSymbol.String)
    Public ReadOnly VarPtr2 As New FunctionSymbol("varptr$", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.Any)), TypeSymbol.String)

    Public ReadOnly Instr1 As New FunctionSymbol("instr", ImmutableArray.Create(New ParameterSymbol("string1", TypeSymbol.String), New ParameterSymbol("string2", TypeSymbol.String)), TypeSymbol.Long)
    Public ReadOnly Instr2 As New FunctionSymbol("instr", ImmutableArray.Create(New ParameterSymbol("start", TypeSymbol.Long), New ParameterSymbol("string1", TypeSymbol.String), New ParameterSymbol("string2", TypeSymbol.String)), TypeSymbol.Long)
    Public ReadOnly Mid1 As New FunctionSymbol("mid$", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.String), New ParameterSymbol("start", TypeSymbol.Long)), TypeSymbol.String)
    Public ReadOnly Mid2 As New FunctionSymbol("mid$", ImmutableArray.Create(New ParameterSymbol("value", TypeSymbol.String), New ParameterSymbol("start", TypeSymbol.Long), New ParameterSymbol("length", TypeSymbol.Long)), TypeSymbol.String)
    Public ReadOnly StringFunction As New FunctionSymbol("string$", ImmutableArray.Create(New ParameterSymbol("num", TypeSymbol.Any), New ParameterSymbol("value", TypeSymbol.Any)), TypeSymbol.String)

    Friend Function GetAll() As IEnumerable(Of FunctionSymbol)
      Dim result = GetType(BuiltinFunctions).GetFields(BindingFlags.Public Or BindingFlags.Static).
                                             Where(Function(f) f.FieldType = GetType(FunctionSymbol)).
                                             Select(Function(f) CType(f.GetValue(Nothing), FunctionSymbol))
      Return result
    End Function

  End Module

End Namespace